language: node_js
node_js:
  - "0.12"
  - "0.11"
sudo: false
addons:
  code_climate:
    repo_token: b239e6a16d96dbec3908794505f104e48726da6d7ee265429b809e03cb7879b8
after_success:
  - node_modules/.bin/codeclimate-test-reporter  < coverage/lcov.info
